// Mocks generated by Mockito 5.2.0 from annotations
// in price_tracker/test/active_symbols/data/data_sources/active_symbols_remote_source_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:price_tracker/active_symbols/data/data_sources/active_symbols_remote_source.dart'
    as _i2;
import 'package:price_tracker/active_symbols/data/models/active_symbols_model.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [ActiveSymbolDataRemoteSourceBase].
///
/// See the documentation for Mockito's code generation for more information.
class MockActiveSymbolDataRemoteSourceBase extends _i1.Mock
    implements _i2.ActiveSymbolDataRemoteSourceBase {
  MockActiveSymbolDataRemoteSourceBase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ActiveSymbolModel>> getActiveSymbols() =>
      (super.noSuchMethod(Invocation.method(#getActiveSymbols, []),
              returnValue: Future<List<_i4.ActiveSymbolModel>>.value(
                  <_i4.ActiveSymbolModel>[]))
          as _i3.Future<List<_i4.ActiveSymbolModel>>);
}
