// Mocks generated by Mockito 5.2.0 from annotations
// in price_tracker/test/active_symbols/domain/repository/get_active_symbols_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:price_tracker/active_symbols/domain/entities/active_symbol.dart'
    as _i6;
import 'package:price_tracker/active_symbols/domain/repository/get_active_symbols_repository.dart'
    as _i3;
import 'package:price_tracker/core/errors/failures.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [ActiveSymbolRepositorybase].
///
/// See the documentation for Mockito's code generation for more information.
class MockActiveSymbolRepositorybase extends _i1.Mock
    implements _i3.ActiveSymbolRepositorybase {
  MockActiveSymbolRepositorybase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ActivSymbol>>>
      getActiveSymbolRepository() => (super.noSuchMethod(
              Invocation.method(#getActiveSymbolRepository, []),
              returnValue:
                  Future<_i2.Either<_i5.Failure, List<_i6.ActivSymbol>>>.value(
                      _FakeEither_0<_i5.Failure, List<_i6.ActivSymbol>>()))
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ActivSymbol>>>);
}
